/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AfterCallRouteImport } from './routes/after.call'
import { Route as AfterDialRouteImport } from './routes/after.dial'
import { Route as AfterDoneRouteImport } from './routes/after.done'
import { Route as AfterGuardianRouteImport } from './routes/after.guardian'
import { Route as AfterOkRouteImport } from './routes/after.ok'
import { Route as AlertIndexRouteImport } from './routes/alert.index'
import { Route as AlertSentRouteImport } from './routes/alert.sent'
import { Route as GuardianAlertRouteImport } from './routes/guardian.alert'
import { Route as GuardianCheckinRouteImport } from './routes/guardian.checkin'
import { Route as GuardianClosedRouteImport } from './routes/guardian.closed'
import { Route as GuardianHomeRouteImport } from './routes/guardian.home'
import { Route as GuardianNoreplyRouteImport } from './routes/guardian.noreply'
import { Route as GuardianNoresponseRouteImport } from './routes/guardian.noresponse'
import { Route as GuardianProgressRouteImport } from './routes/guardian.progress'
import { Route as GuardianReplyRouteImport } from './routes/guardian.reply'
import { Route as GuardianResponseRouteImport } from './routes/guardian.response'
import { Route as HomeIndexRouteImport } from './routes/home.index'
import { Route as HomeContactsRouteImport } from './routes/home.contacts'
import { Route as HomeDevicesRouteImport } from './routes/home.devices'
import { Route as JoinCodeRouteImport } from './routes/join.code'
import { Route as JoinConfirmRouteImport } from './routes/join.confirm'
import { Route as JoinDoneRouteImport } from './routes/join.done'
import { Route as JoinRoleRouteImport } from './routes/join.role'
import { Route as VitalsCritRouteImport } from './routes/vitals.crit'
import { Route as VitalsNormalRouteImport } from './routes/vitals.normal'
import { Route as VitalsWarnRouteImport } from './routes/vitals.warn'
import { Route as GuardianJoinCodeRouteImport } from './routes/guardian.join.code'
import { Route as GuardianJoinConfirmRouteImport } from './routes/guardian.join.confirm'
import { Route as GuardianJoinContactsRouteImport } from './routes/guardian.join.contacts'
import { Route as GuardianJoinDoneRouteImport } from './routes/guardian.join.done'
import { Route as GuardianJoinHealthRouteImport } from './routes/guardian.join.health'
import { Route as GuardianJoinPatientRouteImport } from './routes/guardian.join.patient'
import { Route as GuardianJoinProfileRouteImport } from './routes/guardian.join.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterCallRoute = AfterCallRouteImport.update({
  id: '/after/call',
  path: '/after/call',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterDialRoute = AfterDialRouteImport.update({
  id: '/after/dial',
  path: '/after/dial',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterDoneRoute = AfterDoneRouteImport.update({
  id: '/after/done',
  path: '/after/done',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterGuardianRoute = AfterGuardianRouteImport.update({
  id: '/after/guardian',
  path: '/after/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const AfterOkRoute = AfterOkRouteImport.update({
  id: '/after/ok',
  path: '/after/ok',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertIndexRoute = AlertIndexRouteImport.update({
  id: '/alert/',
  path: '/alert/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertSentRoute = AlertSentRouteImport.update({
  id: '/alert/sent',
  path: '/alert/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianAlertRoute = GuardianAlertRouteImport.update({
  id: '/guardian/alert',
  path: '/guardian/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianCheckinRoute = GuardianCheckinRouteImport.update({
  id: '/guardian/checkin',
  path: '/guardian/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianClosedRoute = GuardianClosedRouteImport.update({
  id: '/guardian/closed',
  path: '/guardian/closed',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianHomeRoute = GuardianHomeRouteImport.update({
  id: '/guardian/home',
  path: '/guardian/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianNoreplyRoute = GuardianNoreplyRouteImport.update({
  id: '/guardian/noreply',
  path: '/guardian/noreply',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianNoresponseRoute = GuardianNoresponseRouteImport.update({
  id: '/guardian/noresponse',
  path: '/guardian/noresponse',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianProgressRoute = GuardianProgressRouteImport.update({
  id: '/guardian/progress',
  path: '/guardian/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianReplyRoute = GuardianReplyRouteImport.update({
  id: '/guardian/reply',
  path: '/guardian/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianResponseRoute = GuardianResponseRouteImport.update({
  id: '/guardian/response',
  path: '/guardian/response',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeContactsRoute = HomeContactsRouteImport.update({
  id: '/home/contacts',
  path: '/home/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDevicesRoute = HomeDevicesRouteImport.update({
  id: '/home/devices',
  path: '/home/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/code',
  path: '/join/code',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinConfirmRoute = JoinConfirmRouteImport.update({
  id: '/join/confirm',
  path: '/join/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinDoneRoute = JoinDoneRouteImport.update({
  id: '/join/done',
  path: '/join/done',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoleRoute = JoinRoleRouteImport.update({
  id: '/join/role',
  path: '/join/role',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsCritRoute = VitalsCritRouteImport.update({
  id: '/vitals/crit',
  path: '/vitals/crit',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsNormalRoute = VitalsNormalRouteImport.update({
  id: '/vitals/normal',
  path: '/vitals/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalsWarnRoute = VitalsWarnRouteImport.update({
  id: '/vitals/warn',
  path: '/vitals/warn',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinCodeRoute = GuardianJoinCodeRouteImport.update({
  id: '/guardian/join/code',
  path: '/guardian/join/code',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinConfirmRoute = GuardianJoinConfirmRouteImport.update({
  id: '/guardian/join/confirm',
  path: '/guardian/join/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinContactsRoute = GuardianJoinContactsRouteImport.update({
  id: '/guardian/join/contacts',
  path: '/guardian/join/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinDoneRoute = GuardianJoinDoneRouteImport.update({
  id: '/guardian/join/done',
  path: '/guardian/join/done',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinHealthRoute = GuardianJoinHealthRouteImport.update({
  id: '/guardian/join/health',
  path: '/guardian/join/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinPatientRoute = GuardianJoinPatientRouteImport.update({
  id: '/guardian/join/patient',
  path: '/guardian/join/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const GuardianJoinProfileRoute = GuardianJoinProfileRouteImport.update({
  id: '/guardian/join/profile',
  path: '/guardian/join/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/after/call': typeof AfterCallRoute
  '/after/dial': typeof AfterDialRoute
  '/after/done': typeof AfterDoneRoute
  '/after/guardian': typeof AfterGuardianRoute
  '/after/ok': typeof AfterOkRoute
  '/alert/sent': typeof AlertSentRoute
  '/guardian/alert': typeof GuardianAlertRoute
  '/guardian/checkin': typeof GuardianCheckinRoute
  '/guardian/closed': typeof GuardianClosedRoute
  '/guardian/home': typeof GuardianHomeRoute
  '/guardian/noreply': typeof GuardianNoreplyRoute
  '/guardian/noresponse': typeof GuardianNoresponseRoute
  '/guardian/progress': typeof GuardianProgressRoute
  '/guardian/reply': typeof GuardianReplyRoute
  '/guardian/response': typeof GuardianResponseRoute
  '/home/contacts': typeof HomeContactsRoute
  '/home/devices': typeof HomeDevicesRoute
  '/join/code': typeof JoinCodeRoute
  '/join/confirm': typeof JoinConfirmRoute
  '/join/done': typeof JoinDoneRoute
  '/join/role': typeof JoinRoleRoute
  '/vitals/crit': typeof VitalsCritRoute
  '/vitals/normal': typeof VitalsNormalRoute
  '/vitals/warn': typeof VitalsWarnRoute
  '/alert/': typeof AlertIndexRoute
  '/home/': typeof HomeIndexRoute
  '/guardian/join/code': typeof GuardianJoinCodeRoute
  '/guardian/join/confirm': typeof GuardianJoinConfirmRoute
  '/guardian/join/contacts': typeof GuardianJoinContactsRoute
  '/guardian/join/done': typeof GuardianJoinDoneRoute
  '/guardian/join/health': typeof GuardianJoinHealthRoute
  '/guardian/join/patient': typeof GuardianJoinPatientRoute
  '/guardian/join/profile': typeof GuardianJoinProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/after/call': typeof AfterCallRoute
  '/after/dial': typeof AfterDialRoute
  '/after/done': typeof AfterDoneRoute
  '/after/guardian': typeof AfterGuardianRoute
  '/after/ok': typeof AfterOkRoute
  '/alert/sent': typeof AlertSentRoute
  '/guardian/alert': typeof GuardianAlertRoute
  '/guardian/checkin': typeof GuardianCheckinRoute
  '/guardian/closed': typeof GuardianClosedRoute
  '/guardian/home': typeof GuardianHomeRoute
  '/guardian/noreply': typeof GuardianNoreplyRoute
  '/guardian/noresponse': typeof GuardianNoresponseRoute
  '/guardian/progress': typeof GuardianProgressRoute
  '/guardian/reply': typeof GuardianReplyRoute
  '/guardian/response': typeof GuardianResponseRoute
  '/home/contacts': typeof HomeContactsRoute
  '/home/devices': typeof HomeDevicesRoute
  '/join/code': typeof JoinCodeRoute
  '/join/confirm': typeof JoinConfirmRoute
  '/join/done': typeof JoinDoneRoute
  '/join/role': typeof JoinRoleRoute
  '/vitals/crit': typeof VitalsCritRoute
  '/vitals/normal': typeof VitalsNormalRoute
  '/vitals/warn': typeof VitalsWarnRoute
  '/alert': typeof AlertIndexRoute
  '/home': typeof HomeIndexRoute
  '/guardian/join/code': typeof GuardianJoinCodeRoute
  '/guardian/join/confirm': typeof GuardianJoinConfirmRoute
  '/guardian/join/contacts': typeof GuardianJoinContactsRoute
  '/guardian/join/done': typeof GuardianJoinDoneRoute
  '/guardian/join/health': typeof GuardianJoinHealthRoute
  '/guardian/join/patient': typeof GuardianJoinPatientRoute
  '/guardian/join/profile': typeof GuardianJoinProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/after/call': typeof AfterCallRoute
  '/after/dial': typeof AfterDialRoute
  '/after/done': typeof AfterDoneRoute
  '/after/guardian': typeof AfterGuardianRoute
  '/after/ok': typeof AfterOkRoute
  '/alert/sent': typeof AlertSentRoute
  '/guardian/alert': typeof GuardianAlertRoute
  '/guardian/checkin': typeof GuardianCheckinRoute
  '/guardian/closed': typeof GuardianClosedRoute
  '/guardian/home': typeof GuardianHomeRoute
  '/guardian/noreply': typeof GuardianNoreplyRoute
  '/guardian/noresponse': typeof GuardianNoresponseRoute
  '/guardian/progress': typeof GuardianProgressRoute
  '/guardian/reply': typeof GuardianReplyRoute
  '/guardian/response': typeof GuardianResponseRoute
  '/home/contacts': typeof HomeContactsRoute
  '/home/devices': typeof HomeDevicesRoute
  '/join/code': typeof JoinCodeRoute
  '/join/confirm': typeof JoinConfirmRoute
  '/join/done': typeof JoinDoneRoute
  '/join/role': typeof JoinRoleRoute
  '/vitals/crit': typeof VitalsCritRoute
  '/vitals/normal': typeof VitalsNormalRoute
  '/vitals/warn': typeof VitalsWarnRoute
  '/alert/': typeof AlertIndexRoute
  '/home/': typeof HomeIndexRoute
  '/guardian/join/code': typeof GuardianJoinCodeRoute
  '/guardian/join/confirm': typeof GuardianJoinConfirmRoute
  '/guardian/join/contacts': typeof GuardianJoinContactsRoute
  '/guardian/join/done': typeof GuardianJoinDoneRoute
  '/guardian/join/health': typeof GuardianJoinHealthRoute
  '/guardian/join/patient': typeof GuardianJoinPatientRoute
  '/guardian/join/profile': typeof GuardianJoinProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/after/call'
    | '/after/dial'
    | '/after/done'
    | '/after/guardian'
    | '/after/ok'
    | '/alert/sent'
    | '/guardian/alert'
    | '/guardian/checkin'
    | '/guardian/closed'
    | '/guardian/home'
    | '/guardian/noreply'
    | '/guardian/noresponse'
    | '/guardian/progress'
    | '/guardian/reply'
    | '/guardian/response'
    | '/home/contacts'
    | '/home/devices'
    | '/join/code'
    | '/join/confirm'
    | '/join/done'
    | '/join/role'
    | '/vitals/crit'
    | '/vitals/normal'
    | '/vitals/warn'
    | '/alert/'
    | '/home/'
    | '/guardian/join/code'
    | '/guardian/join/confirm'
    | '/guardian/join/contacts'
    | '/guardian/join/done'
    | '/guardian/join/health'
    | '/guardian/join/patient'
    | '/guardian/join/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/after/call'
    | '/after/dial'
    | '/after/done'
    | '/after/guardian'
    | '/after/ok'
    | '/alert/sent'
    | '/guardian/alert'
    | '/guardian/checkin'
    | '/guardian/closed'
    | '/guardian/home'
    | '/guardian/noreply'
    | '/guardian/noresponse'
    | '/guardian/progress'
    | '/guardian/reply'
    | '/guardian/response'
    | '/home/contacts'
    | '/home/devices'
    | '/join/code'
    | '/join/confirm'
    | '/join/done'
    | '/join/role'
    | '/vitals/crit'
    | '/vitals/normal'
    | '/vitals/warn'
    | '/alert'
    | '/home'
    | '/guardian/join/code'
    | '/guardian/join/confirm'
    | '/guardian/join/contacts'
    | '/guardian/join/done'
    | '/guardian/join/health'
    | '/guardian/join/patient'
    | '/guardian/join/profile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/after/call'
    | '/after/dial'
    | '/after/done'
    | '/after/guardian'
    | '/after/ok'
    | '/alert/sent'
    | '/guardian/alert'
    | '/guardian/checkin'
    | '/guardian/closed'
    | '/guardian/home'
    | '/guardian/noreply'
    | '/guardian/noresponse'
    | '/guardian/progress'
    | '/guardian/reply'
    | '/guardian/response'
    | '/home/contacts'
    | '/home/devices'
    | '/join/code'
    | '/join/confirm'
    | '/join/done'
    | '/join/role'
    | '/vitals/crit'
    | '/vitals/normal'
    | '/vitals/warn'
    | '/alert/'
    | '/home/'
    | '/guardian/join/code'
    | '/guardian/join/confirm'
    | '/guardian/join/contacts'
    | '/guardian/join/done'
    | '/guardian/join/health'
    | '/guardian/join/patient'
    | '/guardian/join/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AfterCallRoute: typeof AfterCallRoute
  AfterDialRoute: typeof AfterDialRoute
  AfterDoneRoute: typeof AfterDoneRoute
  AfterGuardianRoute: typeof AfterGuardianRoute
  AfterOkRoute: typeof AfterOkRoute
  AlertSentRoute: typeof AlertSentRoute
  GuardianAlertRoute: typeof GuardianAlertRoute
  GuardianCheckinRoute: typeof GuardianCheckinRoute
  GuardianClosedRoute: typeof GuardianClosedRoute
  GuardianHomeRoute: typeof GuardianHomeRoute
  GuardianNoreplyRoute: typeof GuardianNoreplyRoute
  GuardianNoresponseRoute: typeof GuardianNoresponseRoute
  GuardianProgressRoute: typeof GuardianProgressRoute
  GuardianReplyRoute: typeof GuardianReplyRoute
  GuardianResponseRoute: typeof GuardianResponseRoute
  HomeContactsRoute: typeof HomeContactsRoute
  HomeDevicesRoute: typeof HomeDevicesRoute
  JoinCodeRoute: typeof JoinCodeRoute
  JoinConfirmRoute: typeof JoinConfirmRoute
  JoinDoneRoute: typeof JoinDoneRoute
  JoinRoleRoute: typeof JoinRoleRoute
  VitalsCritRoute: typeof VitalsCritRoute
  VitalsNormalRoute: typeof VitalsNormalRoute
  VitalsWarnRoute: typeof VitalsWarnRoute
  AlertIndexRoute: typeof AlertIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  GuardianJoinCodeRoute: typeof GuardianJoinCodeRoute
  GuardianJoinConfirmRoute: typeof GuardianJoinConfirmRoute
  GuardianJoinContactsRoute: typeof GuardianJoinContactsRoute
  GuardianJoinDoneRoute: typeof GuardianJoinDoneRoute
  GuardianJoinHealthRoute: typeof GuardianJoinHealthRoute
  GuardianJoinPatientRoute: typeof GuardianJoinPatientRoute
  GuardianJoinProfileRoute: typeof GuardianJoinProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after/call': {
      id: '/after/call'
      path: '/after/call'
      fullPath: '/after/call'
      preLoaderRoute: typeof AfterCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after/dial': {
      id: '/after/dial'
      path: '/after/dial'
      fullPath: '/after/dial'
      preLoaderRoute: typeof AfterDialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after/done': {
      id: '/after/done'
      path: '/after/done'
      fullPath: '/after/done'
      preLoaderRoute: typeof AfterDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after/guardian': {
      id: '/after/guardian'
      path: '/after/guardian'
      fullPath: '/after/guardian'
      preLoaderRoute: typeof AfterGuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/after/ok': {
      id: '/after/ok'
      path: '/after/ok'
      fullPath: '/after/ok'
      preLoaderRoute: typeof AfterOkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/': {
      id: '/alert/'
      path: '/alert'
      fullPath: '/alert/'
      preLoaderRoute: typeof AlertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert/sent': {
      id: '/alert/sent'
      path: '/alert/sent'
      fullPath: '/alert/sent'
      preLoaderRoute: typeof AlertSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/alert': {
      id: '/guardian/alert'
      path: '/guardian/alert'
      fullPath: '/guardian/alert'
      preLoaderRoute: typeof GuardianAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/checkin': {
      id: '/guardian/checkin'
      path: '/guardian/checkin'
      fullPath: '/guardian/checkin'
      preLoaderRoute: typeof GuardianCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/closed': {
      id: '/guardian/closed'
      path: '/guardian/closed'
      fullPath: '/guardian/closed'
      preLoaderRoute: typeof GuardianClosedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/home': {
      id: '/guardian/home'
      path: '/guardian/home'
      fullPath: '/guardian/home'
      preLoaderRoute: typeof GuardianHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/noreply': {
      id: '/guardian/noreply'
      path: '/guardian/noreply'
      fullPath: '/guardian/noreply'
      preLoaderRoute: typeof GuardianNoreplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/noresponse': {
      id: '/guardian/noresponse'
      path: '/guardian/noresponse'
      fullPath: '/guardian/noresponse'
      preLoaderRoute: typeof GuardianNoresponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/progress': {
      id: '/guardian/progress'
      path: '/guardian/progress'
      fullPath: '/guardian/progress'
      preLoaderRoute: typeof GuardianProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/reply': {
      id: '/guardian/reply'
      path: '/guardian/reply'
      fullPath: '/guardian/reply'
      preLoaderRoute: typeof GuardianReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/response': {
      id: '/guardian/response'
      path: '/guardian/response'
      fullPath: '/guardian/response'
      preLoaderRoute: typeof GuardianResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/contacts': {
      id: '/home/contacts'
      path: '/home/contacts'
      fullPath: '/home/contacts'
      preLoaderRoute: typeof HomeContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/devices': {
      id: '/home/devices'
      path: '/home/devices'
      fullPath: '/home/devices'
      preLoaderRoute: typeof HomeDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/code': {
      id: '/join/code'
      path: '/join/code'
      fullPath: '/join/code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/confirm': {
      id: '/join/confirm'
      path: '/join/confirm'
      fullPath: '/join/confirm'
      preLoaderRoute: typeof JoinConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/done': {
      id: '/join/done'
      path: '/join/done'
      fullPath: '/join/done'
      preLoaderRoute: typeof JoinDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/role': {
      id: '/join/role'
      path: '/join/role'
      fullPath: '/join/role'
      preLoaderRoute: typeof JoinRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals/crit': {
      id: '/vitals/crit'
      path: '/vitals/crit'
      fullPath: '/vitals/crit'
      preLoaderRoute: typeof VitalsCritRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals/normal': {
      id: '/vitals/normal'
      path: '/vitals/normal'
      fullPath: '/vitals/normal'
      preLoaderRoute: typeof VitalsNormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitals/warn': {
      id: '/vitals/warn'
      path: '/vitals/warn'
      fullPath: '/vitals/warn'
      preLoaderRoute: typeof VitalsWarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/code': {
      id: '/guardian/join/code'
      path: '/guardian/join/code'
      fullPath: '/guardian/join/code'
      preLoaderRoute: typeof GuardianJoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/confirm': {
      id: '/guardian/join/confirm'
      path: '/guardian/join/confirm'
      fullPath: '/guardian/join/confirm'
      preLoaderRoute: typeof GuardianJoinConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/contacts': {
      id: '/guardian/join/contacts'
      path: '/guardian/join/contacts'
      fullPath: '/guardian/join/contacts'
      preLoaderRoute: typeof GuardianJoinContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/done': {
      id: '/guardian/join/done'
      path: '/guardian/join/done'
      fullPath: '/guardian/join/done'
      preLoaderRoute: typeof GuardianJoinDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/health': {
      id: '/guardian/join/health'
      path: '/guardian/join/health'
      fullPath: '/guardian/join/health'
      preLoaderRoute: typeof GuardianJoinHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/patient': {
      id: '/guardian/join/patient'
      path: '/guardian/join/patient'
      fullPath: '/guardian/join/patient'
      preLoaderRoute: typeof GuardianJoinPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guardian/join/profile': {
      id: '/guardian/join/profile'
      path: '/guardian/join/profile'
      fullPath: '/guardian/join/profile'
      preLoaderRoute: typeof GuardianJoinProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AfterCallRoute: AfterCallRoute,
  AfterDialRoute: AfterDialRoute,
  AfterDoneRoute: AfterDoneRoute,
  AfterGuardianRoute: AfterGuardianRoute,
  AfterOkRoute: AfterOkRoute,
  AlertSentRoute: AlertSentRoute,
  GuardianAlertRoute: GuardianAlertRoute,
  GuardianCheckinRoute: GuardianCheckinRoute,
  GuardianClosedRoute: GuardianClosedRoute,
  GuardianHomeRoute: GuardianHomeRoute,
  GuardianNoreplyRoute: GuardianNoreplyRoute,
  GuardianNoresponseRoute: GuardianNoresponseRoute,
  GuardianProgressRoute: GuardianProgressRoute,
  GuardianReplyRoute: GuardianReplyRoute,
  GuardianResponseRoute: GuardianResponseRoute,
  HomeContactsRoute: HomeContactsRoute,
  HomeDevicesRoute: HomeDevicesRoute,
  JoinCodeRoute: JoinCodeRoute,
  JoinConfirmRoute: JoinConfirmRoute,
  JoinDoneRoute: JoinDoneRoute,
  JoinRoleRoute: JoinRoleRoute,
  VitalsCritRoute: VitalsCritRoute,
  VitalsNormalRoute: VitalsNormalRoute,
  VitalsWarnRoute: VitalsWarnRoute,
  AlertIndexRoute: AlertIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  GuardianJoinCodeRoute: GuardianJoinCodeRoute,
  GuardianJoinConfirmRoute: GuardianJoinConfirmRoute,
  GuardianJoinContactsRoute: GuardianJoinContactsRoute,
  GuardianJoinDoneRoute: GuardianJoinDoneRoute,
  GuardianJoinHealthRoute: GuardianJoinHealthRoute,
  GuardianJoinPatientRoute: GuardianJoinPatientRoute,
  GuardianJoinProfileRoute: GuardianJoinProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
